export const LOGIN = 'LOGIN';
export const APPLICATIONS = 'APPLICATIONS';
export const APPLICATION = 'APPLICATION';

export const CLUSTER_CREATE = 'CLUSTER_CREATE';
export const CLUSTER_DETAIL = 'CLUSTER_DETAIL';
export const CLUSTER_EDIT = 'CLUSTER_EDIT';
export const CLUSTER_LIST = 'CLUSTER_LIST';
export const CLUSTER_REMOVE = 'CLUSTER_REMOVE';
