export const LOGIN = 'LOGIN';

export const CLUSTER_CREATE = 'CLUSTER_CREATE';
export const CLUSTER_DETAIL = 'CLUSTER_DETAIL';
export const CLUSTER_EDIT = 'CLUSTER_EDIT';
export const CLUSTER_LIST = 'CLUSTER_LIST';
export const CLUSTER_REMOVE = 'CLUSTER_REMOVE';

export const PROVIDER_CREATE = 'PROVIDER_CREATE';
export const PROVIDER_DETAIL = 'PROVIDER_DETAIL';
export const PROVIDER_EDIT = 'PROVIDER_EDIT';
export const PROVIDER_LIST = 'PROVIDER_LIST';
export const PROVIDER_REMOVE = 'PROVIDER_REMOVE';

export const APPLICATION_CREATE = 'APPLICATION_CREATE';
export const APPLICATION_DETAIL = 'APPLICATION_DETAIL';
export const APPLICATION_EDIT = 'APPLICATION_EDIT';
export const APPLICATION_LIST = 'APPLICATION_LIST';
export const APPLICATION_REMOVE = 'APPLICATION_REMOVE';
