export const APPLICATION_CREATE = 'APPLICATION_CREATE';
export const APPLICATION_DETAIL = 'APPLICATION_DETAIL';
export const APPLICATION_EDIT = 'APPLICATION_EDIT';
export const APPLICATION_LIST = 'APPLICATION_LIST';
export const APPLICATION_REMOVE = 'APPLICATION_REMOVE';
export const APPLICATION_PROVISION = 'APPLICATION_PROVISION';
